name: Python FAST API Build and Deploy to EC2 Instance

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-fast-api:latest

    - name: "Configure AWS Credentials" 
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }} 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Amazon ECR "Login" Action for GitHub Actions
      uses: aws-actions/amazon-ecr-login@v2

    - name: Push the Docker Image to ECR
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v0m7a4i7
        docker tag my-fast-api:latest public.ecr.aws/v0m7a4i7/my-fast-api:latest
        docker push public.ecr.aws/v0m7a4i7/my-fast-api:latest

    - name: Action-SSH
      uses: tiyee/action-ssh@v1.0.1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        privateKey: ${{ secrets.EC2_SSH_KEY }}
        command: docker pull public.ecr.aws/v0m7a4i7/my-fast-api:latest && docker run -d -p 80:80 --name my-fast-api public.ecr.aws/v0m7a4i7/my-fast-api:latest